# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: P13/front/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: P13/front

      - name: Run tests and generate reports
        run: npm test -- --watch=false --browsers=ChromeHeadless --code-coverage
        working-directory: P13/front

      - name: Upload Karma report artifact
        uses: actions/upload-artifact@v4
        with:
          name: Karma-report
          path: P13/front/coverage
